name: ticket_manager
description: An application that will allow a service team track and manager open, closed, and active tickets. As well as giving the recipient of the service a timeline of completion

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.12+4
  firebase_core: "^0.5.1"
  firebase_auth: "^0.18.2"
  firebase_database: "^4.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/icon/ 

